import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {inspectBook,applyMapping,mappingText} from '../../src/core.mjs';import {reportHTML} from '../../src/report.mjs';import {DEMO_RECORDS,DEMO_SOURCE} from '../../src/demo-data.mjs';import {modify} from '../helpers.mjs';import {installWorkerGate} from './worker-gate.mjs';
const fixture=new Uint8Array(await readFile('tests/fixtures/field-notes.epub')),expected=JSON.parse(await readFile('tests/fixtures/expected-selection.json','utf8')),out='tests/browser/artifacts';await mkdir(out,{recursive:true});
const base=process.env.BASE_URL||'http://127.0.0.1:4179',checks=[],errors=[],requests=[];
const browser=await chromium.launch({headless:true,chromiumSandbox:true}),context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>requests.push(r.url()));
const step=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
async function assertNoOverflow(width){
 const bounds=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].map(element=>{const r=element.getBoundingClientRect();return {tag:element.tagName,id:element.id,className:element.className,left:r.left,right:r.right,clientWidth:element.clientWidth,scrollWidth:element.scrollWidth};}).filter(r=>r.right>innerWidth||r.left<0||r.scrollWidth>r.clientWidth+1).slice(0,60)}));
 if(bounds.document>bounds.viewport)await writeFile(`${out}/overflow-${width}.json`,JSON.stringify(bounds,null,2));
 assert.ok(bounds.document<=bounds.viewport,`overflow ${width}: document ${bounds.document}, viewport ${bounds.viewport}`);
}

let lastDownload=0;
async function download(id,name){const remaining=750-(Date.now()-lastDownload);if(remaining>0)await page.waitForTimeout(remaining);const ready=page.waitForEvent('download');await page.locator('#'+id).click();const file=await ready;lastDownload=Date.now();await file.saveAs(`${out}/${name}`);return new Uint8Array(await readFile(`${out}/${name}`));}
async function setDate(){await page.locator('.settings summary').click();await page.locator('#modified').fill(expected.modifiedAfter);await page.locator('.settings summary').click();}
async function assertSkipHidden(){await expect(page.locator('.skip-link')).not.toBeFocused();await expect(page.locator('.skip-link')).toHaveCSS('opacity','0');await expect(page.locator('.skip-link')).toHaveCSS('clip-path','inset(50%)');}
async function demo(){await page.locator('#demo').click();await expect(page.locator('#busy')).toBeHidden();await expect(page.locator('#book-heading')).toHaveText('Field Notes Along the River');await expect(page.locator('#records')).toContainText('Field notes begin');await setDate();await assertSkipHidden();}
async function searchDemo(){await page.locator('#search').click();await expect(page.locator('.boundary')).toHaveCount(8);await expect(page.locator('#busy')).toBeHidden();}
async function choosePreview(){await page.locator('#demo-selection').click();await expect(page.locator('input[data-row]:checked')).toHaveCount(8);await page.locator('#preview').click();await expect(page.locator('.preview-list li')).toHaveCount(8);await expect(page.locator('#busy')).toBeHidden();}
async function exportNow(){await page.locator('#export').click();await expect(page.locator('#export-result')).toBeVisible();await expect(page.locator('#busy')).toBeHidden();}
async function upload(bytes,name){await page.locator('#file').setInputFiles({name,mimeType:'application/epub+zip',buffer:Buffer.from(bytes)});await expect(page.locator('#busy')).toBeHidden();await expect(page.locator('.book-summary')).toContainText(name);}
async function restore(mapping,name='mapping.json'){await page.locator('#mapping-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mapping,null,2)+'\n')});await expect(page.locator('#busy')).toBeHidden();}
let output,mapping,receipt;
try{
await step('Japanese entry, keyboard skip and original three-document demo load',async()=>{await page.goto(base);await expect(page.locator('html')).toHaveAttribute('lang','ja');await page.keyboard.press('Tab');await expect(page.locator('.skip-link')).toBeFocused();await expect(page.locator('.skip-link')).toHaveCSS('opacity','1');await expect(page.locator('.skip-link')).toHaveCSS('clip-path','none');await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();await assertSkipHidden();await demo();await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});await page.setViewportSize({width:390,height:1040});await assertNoOverflow(390);await page.screenshot({path:`${out}/mobile-ja.png`,fullPage:true});await page.setViewportSize({width:1440,height:1040});});
await step('English candidate review exposes four repeats and requires explicit choices',async()=>{await page.locator('[data-lang="en"]').click();await searchDemo();await expect(page.locator('.boundary').nth(2).locator('.candidate')).toHaveCount(4);await expect(page.locator('input[data-row]:checked')).toHaveCount(0);await expect(page.locator('#preview')).toBeDisabled();await page.locator('#candidate-0-0').focus();await page.keyboard.press('Space');await expect(page.locator('#candidate-0-0')).toBeChecked();await choosePreview();await expect(page.locator('.preview-list li').first()).toContainText('iv');await expect(page.locator('.preview-list li').last()).toContainText('A-1');await page.screenshot({path:`${out}/desktop-en-preview.png`,fullPage:true});});
await step('four actual downloads match the engine and independent intended-selection oracle',async()=>{await exportNow();output=await download('download-epub','paginated.epub');mapping=JSON.parse(new TextDecoder().decode(await download('download-mapping','mapping.json')));receipt=JSON.parse(new TextDecoder().decode(await download('download-receipt','receipt.json')));const html=new TextDecoder().decode(await download('download-report','review.html'));const reference=await applyMapping(await inspectBook(fixture,'field-notes.epub'),mapping);assert.deepEqual(output,reference.output);assert.deepEqual(receipt,reference.receipt);assert.equal(html,reportHTML(reference.receipt));assert.equal(mapping.modifiedAfter,expected.modifiedAfter);assert.equal(await readFile(`${out}/mapping.json`,'utf8'),mappingText(mapping));execFileSync('python3',['tests/oracle.py','tests/fixtures/field-notes.epub',`${out}/paginated.epub`,`${out}/receipt.json`,'--expected-selection','tests/fixtures/expected-selection.json','--mapping',`${out}/mapping.json`],{stdio:'inherit'});});
await step('repeated export is byte-identical and source/choice edits invalidate downloads',async()=>{await exportNow();assert.deepEqual(await download('download-epub','repeated.epub'),output);await page.locator('#source').fill(DEMO_SOURCE+' revised');await expect(page.locator('#export-result')).toHaveCount(0);await expect(page.locator('#preview-panel')).toHaveCount(0);await page.locator('#source').fill(DEMO_SOURCE);await page.locator('#candidate-2-1').check();await expect(page.locator('#preview-panel')).toHaveCount(0);await page.locator('#candidate-2-2').check();await page.locator('#preview').click();await expect(page.locator('.preview-list li')).toHaveCount(8);});
await step('saved mapping restores all choices after reset/reimport and repeated same-file restore',async()=>{await page.locator('#reset').click();await expect(page.locator('.empty-state')).toBeVisible();await upload(fixture,'retained.epub');for(let i=0;i<2;i++){await restore(mapping);await expect(page.locator('.preview-list li')).toHaveCount(8);await expect(page.locator('input[data-row]:checked')).toHaveCount(8);}const multiline={...mapping,boundaries:mapping.boundaries.map((row,i)=>({...row,phrase:i===0?row.phrase.replace(' ','\r\n'):row.phrase}))};await restore(multiline,'multiline.json');await page.locator('#search').click();await expect(page.locator('.boundary')).toHaveCount(8);await expect(page.locator('#busy')).toBeHidden();await expect(page.locator('#status')).not.toHaveClass(/error/);await restore(mapping);await exportNow();assert.deepEqual(await download('download-epub','restored.epub'),output);});
await step('stale mapping, duplicate keys, reverse order and malformed UTF-8 reject without replacing the book',async()=>{await restore({...mapping,inputSha256:'0'.repeat(64)},'stale.json');await expect(page.locator('#status')).toContainText('stale-mapping');await page.locator('#mapping-file').setInputFiles({name:'duplicate.json',mimeType:'application/json',buffer:Buffer.from('{"schema":"ignored",'+JSON.stringify(mapping).slice(1))});await expect(page.locator('#status')).toContainText('mapping-json');await restore({...mapping,boundaries:[...mapping.boundaries].reverse()},'reversed.json');await expect(page.locator('#status')).toContainText('boundary-order');const raw=Buffer.from(JSON.stringify({...mapping,metadata:'MARK'}));raw[raw.indexOf('MARK')]=0xff;await page.locator('#mapping-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:raw});await expect(page.locator('#status')).toContainText('encoding');await expect(page.locator('.book-summary')).toContainText('retained.epub');});
await step('missing quotes stay unresolved and single candidates are never chosen automatically',async()=>{await page.locator('#records').fill('42\tNo such phrase exists here');await page.locator('#search').click();await expect(page.locator('.boundary')).toHaveCount(1);await expect(page.locator('.candidate')).toHaveCount(0);await expect(page.locator('#preview')).toBeDisabled();await page.locator('#records').fill('42\tquiet attention');await page.locator('#search').click();await expect(page.locator('.candidate')).toHaveCount(1);await expect(page.locator('#preview')).toBeDisabled();await page.locator('#candidate-0-0').check();await expect(page.locator('#preview')).toBeEnabled();await restore(mapping);});
await step('malformed and already-paginated replacement imports preserve the last good book',async()=>{await page.locator('#file').setInputFiles({name:'broken.epub',mimeType:'application/epub+zip',buffer:Buffer.from('broken')});await expect(page.locator('#status')).toContainText('input-size');await expect(page.locator('.book-summary')).toContainText('retained.epub');await page.locator('#file').setInputFiles({name:'already-paginated.epub',mimeType:'application/epub+zip',buffer:Buffer.from(output)});await expect(page.locator('#status')).toContainText('existing-pagination');await expect(page.locator('.book-summary')).toContainText('retained.epub');});
await step('cancel, oversized replacement and reset block real stale worker responses deterministically',async()=>{await page.evaluate(installWorkerGate);const status=()=>page.evaluate(()=>window.__workerGate.status());const held=async i=>{await expect.poll(async()=>(await status())[i]?.queued).toBe(1);await expect(page.locator('#busy')).toBeVisible();};const release=async i=>{assert.equal((await status())[i].terminated,true);assert.equal(await page.evaluate(index=>window.__workerGate.release(index),i),1);};try{await page.locator('#demo').click();await held(0);await page.locator('#cancel').click();await release(0);await expect(page.locator('.book-summary')).toContainText('retained.epub');await page.locator('#demo').click();await held(1);await page.locator('#file').setInputFiles({name:'huge.epub',mimeType:'application/epub+zip',buffer:Buffer.alloc(25*1024*1024+1)});await expect(page.locator('#status')).toContainText('input-size');await release(1);await expect(page.locator('.book-summary')).toContainText('retained.epub');await expect(page.locator('#status')).toContainText('input-size');await page.locator('#demo').click();await held(2);await page.locator('#reset').click();await release(2);await expect(page.locator('.empty-state')).toBeVisible();await expect(page.locator('#preview-panel')).toHaveCount(0);await expect(page.locator('#export-result')).toHaveCount(0);await expect(page.locator('#busy')).toBeHidden();}finally{await page.evaluate(()=>window.__workerGate.restore());}});
await step('offline-after-load import, saved decisions and export require no network',async()=>{await context.setOffline(true);await upload(fixture,'offline.epub');await restore(mapping);await exportNow();assert.deepEqual(await download('download-epub','offline.epub'),output);await context.setOffline(false);});
await step('hostile source labels and metadata are escaped and no imported resource is rendered',async()=>{const hostile=await modify(fixture,'EPUB/package.opf',s=>s.replace('Field Notes Along the River','&lt;img src=x onerror=alert(1)&gt;'));await upload(hostile,'hostile.epub');await expect(page.locator('#book-heading')).toHaveText('<img src=x onerror=alert(1)>');await expect(page.locator('#book-heading img')).toHaveCount(0);assert.ok(requests.every(u=>u.startsWith(base+'/')||u.startsWith('blob:')));});
await step('language switches retain confirmed choices and narrow layouts remain usable',async()=>{await demo();await searchDemo();await choosePreview();for(const language of ['ja','en']){await page.locator(`[data-lang="${language}"]`).click();await expect(page.locator('input[data-row]:checked')).toHaveCount(8);await expect(page.locator('.preview-list li')).toHaveCount(8);}for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1040});await assertNoOverflow(width);await page.screenshot({path:`${out}/responsive-${width}.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1040});});
await step('actual standalone report prints with hashes, source and limitations visible',async()=>{const reportPage=await context.newPage();await reportPage.setContent(await readFile(`${out}/review.html`,'utf8'));await reportPage.emulateMedia({media:'print'});await expect(reportPage.locator('footer')).toContainText('does not certify');await expect(reportPage.locator('.boundary')).toHaveCount(8);await reportPage.pdf({path:`${out}/review.pdf`,format:'A4',printBackground:true});await reportPage.screenshot({path:`${out}/review-print.png`,fullPage:true});await reportPage.close();});
await step('reloading clears private state and there are no duplicate IDs or uncaught errors',async()=>{assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return ids.length===new Set(ids).size;}),true);await page.reload();await expect(page.locator('.empty-state')).toBeVisible();assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(base+'/')||u.startsWith('blob:')));});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks,uncaughtErrors:errors,readingSystemTested:false,editorialBoundaryCorrectnessTested:false},null,2));
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks,error:String(error),uncaughtErrors:errors},null,2));throw error;}finally{await context.close();await browser.close();}
