import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {inspectBook,findCandidates,resolvePath} from '../src/core.mjs';import {LIMITS} from '../src/limits.mjs';import {xml} from '../src/xml.mjs';import {directory,openZip,decode,writeZip,encode} from '../src/zip.mjs';import {packEntries,modify,addEntry} from './helpers.mjs';
const fixture=new Uint8Array(await readFile(new URL('./fixtures/field-notes.epub',import.meta.url)));const content='EPUB/text/mm-trail.xhtml';
test('ZIP duplicate, case alias, unsafe and ambiguous encoding paths reject',()=>{for(const names of [['a','a'],['A','a'],['../a'],['/a'],['a\\b'],['a//b'],['a%2fb'],['e\u0301']])assert.throws(()=>directory(packEntries(names.map(n=>[n,'x']))));const zip=packEntries([['é','x']]),v=new DataView(zip.buffer);for(let i=0;i<zip.length-4;i++){const sig=v.getUint32(i,true);if(sig===0x04034b50)v.setUint16(i+6,0,true);if(sig===0x02014b50)v.setUint16(i+8,0,true);}assert.throws(()=>directory(zip),e=>e.code==='zip-encoding');});
test('ZIP input/inflation bounds and CRC errors reject',async()=>{assert.throws(()=>directory(new Uint8Array(LIMITS.inputBytes+1)),e=>e.code==='input-size');const z=packEntries([['x','y']]);z[31]^=1;await assert.rejects(()=>openZip(z),e=>e.code==='zip-integrity');const large=packEntries([['x','y']]);new DataView(large.buffer).setUint32(32+24,LIMITS.entryBytes+1,true);assert.throws(()=>directory(large),e=>e.code==='zip-limit');});
test('OCF mimetype content, first-entry rule and single-package container are enforced',async()=>{const z=await openZip(fixture);await assert.rejects(()=>inspectBook(packEntries([...z.entries].reverse().map(([n,e])=>[n,e.bytes]))),e=>e.code==='epub-mimetype');await assert.rejects(()=>modify(fixture,'mimetype',()=> 'application/zip').then(inspectBook),e=>e.code==='epub-mimetype');await assert.rejects(()=>modify(fixture,'META-INF/container.xml',s=>s.replace('</rootfiles>','<rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles>')).then(inspectBook),e=>e.code==='multiple-packages');});
test('encrypted/signed, fixed-layout and media-overlay packages fail closed',async()=>{for(const name of ['META-INF/encryption.xml','META-INF/signatures.xml'])await assert.rejects(()=>addEntry(fixture,name,'<x/>').then(inspectBook),e=>e.code==='protected-package');for(const fn of [s=>s.replace('</metadata>','<meta property="rendition:layout">pre-paginated</meta></metadata>'),s=>s.replace('id="trail" href','media-overlay="overlay" id="trail" href')])await assert.rejects(()=>modify(fixture,'EPUB/package.opf',fn).then(inspectBook),e=>['fixed-layout','unsupported-profile'].includes(e.code));});
test('scripts, event attributes and JavaScript URLs reject in XHTML and SVG',async()=>{for(const [part,fn]of [[content,s=>s.replace('</body>','<script>alert(1)</script></body>')],[content,s=>s.replace('</body>','<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg></body>')],[content,s=>s.replace('<p>The','<p onclick="x()">The')],[content,s=>s.replace('<em>','<em><a href="java&#10;script:alert(1)">x</a>')],['EPUB/images/river.svg',s=>s.replace('</svg>','<script>alert(1)</script></svg>')],['EPUB/images/river.svg',s=>s.replace('<path','<path onload="x()"')]])await assert.rejects(()=>modify(fixture,part,fn).then(inspectBook),e=>e.code==='scripted-content');});
test('duplicate manifest/spine/document IDs and base URI overrides reject',async()=>{for(const [part,fn,code]of [['EPUB/package.opf',s=>s.replace('id="river"','id="intro"'),'duplicate-id'],['EPUB/package.opf',s=>s.replace('<itemref idref="river"/>','<itemref idref="trail"/>'),'spine-identity'],[content,s=>s.replace('<p>The','<p xml:base="https://invalid.example/">The'),'base-uri']])await assert.rejects(()=>modify(fixture,part,fn).then(inspectBook),e=>e.code===code);});
test('DTD, invalid XML whitespace, malformed namespace and invalid UTF-8 reject',async()=>{for(const s of ['<!DOCTYPE r SYSTEM "https://invalid.example"><r/>','<r\u00a0a="1"/>','\u00a0<r/>','<!--x--><?xml version="1.0"?><r/>','<r xmlns:xml="urn:wrong"/>','<r xmlns:p="urn:x"><p:/></r>'])assert.throws(()=>xml(s));await assert.rejects(()=>modify(fixture,content,s=>'<!DOCTYPE html SYSTEM "https://invalid.example/dtd">'+s).then(inspectBook),e=>e.code==='xml-doctype');const z=await openZip(fixture),bad=encode(decode(z.entries.get(content).bytes));bad[10]=0xff;await assert.rejects(()=>inspectBook(writeZip(z,new Map([[content,bad]]))),e=>e.code==='encoding');});
test('a non-plain modified timestamp cannot silently remove comments or CDATA',async()=>{for(const value of ['<!--retain-->2026-01-01T00:00:00Z','<![CDATA[2026-01-01T00:00:00Z]]>'])await assert.rejects(()=>modify(fixture,'EPUB/package.opf',s=>s.replace('>2026-01-01T00:00:00Z<','>'+value+'<')).then(inspectBook),e=>e.code==='modified-metadata');});
test('resource URLs resolve literal encoded filenames and never leave the container',()=>{assert.equal(resolvePath('EPUB/package.opf','text/chapter%201.xhtml'),'EPUB/text/chapter 1.xhtml');assert.equal(resolvePath('EPUB/nav.xhtml','text/%E5%B7%9D.xhtml'),'EPUB/text/川.xhtml');for(const href of ['../../bad','https://example.com/x','//example.com/x','x#id','x?query','x%2fy','x%5cy','x%ZZ'])assert.throws(()=>resolvePath('EPUB/p.opf',href));});
test('search-work budget rejects a bounded but expensive multi-record request',async()=>{const b=await modify(fixture,content,s=>s.replace('The trail opened with ',('ordinary words '.repeat(75000))));const c=await inspectBook(b);const records=Array.from({length:110},(_,i)=>({decisionId:'p'+i,label:String(i),phrase:'missing-'+i}));assert.throws(()=>findCandidates(c,records),e=>e.code==='search-work-limit');});
test('XML namespace binding and text-node allocation caps reject early',()=>{assert.throws(()=>xml('<r '+Array.from({length:129},(_,i)=>`xmlns:p${i}="urn:x"`).join(' ')+'/>'),e=>e.code==='xml-attribute-limit');assert.throws(()=>xml('<r>'+'a<!--x-->'.repeat(LIMITS.textNodes+1)+'</r>'),e=>e.code==='xml-text-limit');});
test('aliased property vocabularies cannot hide fixed layout, scripts or existing page semantics',async()=>{
 const pref='prefix="r: http://www.idpf.org/vocab/rendition/# f: http://idpf.org/epub/vocab/package/item/# m: http://idpf.org/epub/vocab/package/meta/#" ';
 for(const fn of [s=>s.replace('<package ','<package '+pref).replace('</metadata>','<meta property="r:layout">pre-paginated</meta></metadata>'),s=>s.replace('<package ','<package '+pref).replace('id="trail" href','properties="f:scripted" id="trail" href'),s=>s.replace('<package ','<package '+pref).replace('</metadata>','<meta property="m:pageBreakSource">Old source</meta></metadata>')])await assert.rejects(()=>modify(fixture,'EPUB/package.opf',fn).then(inspectBook),e=>['fixed-layout','unsupported-profile','existing-pagination','default-vocabulary-prefix'].includes(e.code));
 await assert.rejects(()=>modify(fixture,content,s=>s.replace('<body>','<body epub:prefix="s: http://www.idpf.org/epub/vocab/structure/#">').replace('<p>The','<p epub:type="s:pagebreak">The')).then(inspectBook),e=>e.code==='property-prefix-location');
});
test('valid explicit canonical and aliased modified vocabularies remain supported',async()=>{
 const b=await modify(fixture,'EPUB/package.opf',s=>s.replace('<package ','<package prefix="rendition: http://www.idpf.org/vocab/rendition/# d: http://purl.org/dc/terms/" ').replace('property="dcterms:modified"','property="d:modified"'));
 const c=await inspectBook(b);assert.equal(c.model.spine.length,3);assert.equal(c.modified.text,'2026-01-01T00:00:00Z');
});
