import {VERSION,LIMITS,fail} from './limits.mjs';
import {openZip,writeZip,encode,decode,sha256,safePath} from './zip.mjs';
import {xml,walk,is,direct,attr} from './xml.mjs';
export {VERSION,LIMITS};
export const NS=Object.freeze({opf:'http://www.idpf.org/2007/opf',ocf:'urn:oasis:names:tc:opendocument:xmlns:container',xhtml:'http://www.w3.org/1999/xhtml',epub:'http://www.idpf.org/2007/ops',dc:'http://purl.org/dc/elements/1.1/',xml:'http://www.w3.org/XML/1998/namespace'});
export const PROFILE='EPUB 3.3 reflowable XHTML; current W3C pagination-source guidance; not final EPUB 3.4 conformance';
export const WHITESPACE='xml-s-collapse-v1';
const blocks=new Set(['p','h1','h2','h3','h4','h5','h6','li']);
const inline=new Set(['a','em','strong','span','b','i','u','s','small','sub','sup','abbr']);
const containers=new Set(['body','section','article','div','main','aside','header','footer','blockquote','ol','ul','li']);
const forbidden=new Set(['script','iframe','object','embed']);
const words=s=>{const text=s??'';if(typeof text!=='string'||text.length>LIMITS.propertyTextChars)fail('property-token-limit');const parts=text.split(/[ \t\r\n]+/).filter(Boolean);if(parts.length>LIMITS.propertyTokens)fail('property-token-limit');return parts;};
const VOCAB={meta:'http://idpf.org/epub/vocab/package/meta/#',item:'http://idpf.org/epub/vocab/package/item/#',itemref:'http://idpf.org/epub/vocab/package/itemref/#',structure:'http://www.idpf.org/epub/vocab/structure/#',rendition:'http://www.idpf.org/vocab/rendition/#',schema:'http://schema.org/',dcterms:'http://purl.org/dc/terms/'};
const RESERVED={a11y:'http://www.idpf.org/epub/vocab/package/a11y/#',dcterms:VOCAB.dcterms,marc:'http://id.loc.gov/vocabulary/',media:'http://www.idpf.org/epub/vocab/overlays/#',onix:'http://www.editeur.org/ONIX/book/codelists/current.html#',rendition:VOCAB.rendition,schema:VOCAB.schema,xsd:'http://www.w3.org/2001/XMLSchema#',msv:'http://www.idpf.org/epub/vocab/structure/magazine/#',prism:'http://www.prismstandard.org/specifications/3.0/PRISM_CV_Spec_3.0.htm#'};
function prefixState(value,parent=null,kind='package'){if(!value&&parent)return parent;const reserved=Object.fromEntries(Object.entries(RESERVED).filter(([key])=>kind==='structure'?['msv','prism'].includes(key):!['msv','prism'].includes(key))),base=parent?.map??Object.assign(Object.create(null),reserved);if(!value)return parent??{map:base,count:Object.keys(reserved).length};if(value.length>LIMITS.namespaceBindings*(LIMITS.namespaceUriChars+130))fail('property-prefix-limit');const pieces=words(value);if(pieces.length%2)fail('property-prefix');const map=Object.create(base),seen=new Set();let count=parent?.count??Object.keys(reserved).length;for(let i=0;i<pieces.length;i+=2){if(!/^[A-Za-z_][\w.-]*:$/.test(pieces[i]))fail('property-prefix');const key=pieces[i].slice(0,-1),uri=pieces[i+1];if(key.length>128||uri.length>LIMITS.namespaceUriChars||!/^[A-Za-z][A-Za-z0-9+.-]*:/.test(uri)||seen.has(key))fail('property-prefix');if(!(key in map)&&++count>LIMITS.namespaceBindings)fail('property-prefix-limit');if(key==='_'||[VOCAB.meta,VOCAB.item,VOCAB.itemref,VOCAB.structure,'http://idpf.org/epub/vocab/package/link/#',NS.dc].includes(uri))fail('default-vocabulary-prefix');if(Object.hasOwn(reserved,key)&&reserved[key]!==uri)fail('reserved-prefix-profile');seen.add(key);Object.defineProperty(map,key,{value:uri,enumerable:true});}return {map,count};}
function propertyIRI(token,state,base){if(typeof token!=='string'||!token)return '';if(token.length>LIMITS.pathChars)fail('property-token-limit');const pieces=token.split(':');if(pieces.length===1)return base+token;if(pieces.length!==2||!pieces[0]||!pieces[1]||!(pieces[0] in state.map))fail('property-prefix');return state.map[pieces[0]]+pieces[1];}

const one=(a,code)=>{if(a.length!==1)fail(code);return a[0];};
export const escapeXML=s=>String(s).replace(/[&<>"'\t\r\n]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;','\t':'&#9;','\r':'&#13;','\n':'&#10;'}[c]));
export function normalizeQuote(s){return s.replace(/[ \t\r\n]+/g,' ').replace(/^ | $/g,'');}
function textValue(value,max,code){if(typeof value!=='string'||!value.length||value.length>max*2||[...value].length>max||!normalizeQuote(value))fail(code);for(const c of value){const n=c.codePointAt(0);if(!(n===9||n===10||n===13||n>=32&&n<=0xd7ff||n>=0xe000&&n<=0xfffd||n>=0x10000&&n<=0x10ffff))fail(code);}return value;}
const RECORD_KEYS=new Set(['decisionId','label','phrase','candidateId']),MAPPING_KEYS=new Set(['schema','inputSha256','paginationSource','modifiedAfter','whitespace','boundaries']);
function plain(value,allowed){if(!value||typeof value!=='object'||Array.isArray(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))fail('mapping-format');const keys=Reflect.ownKeys(value),copy=Object.create(null);if(allowed&&keys.length>allowed.size)fail('mapping-format');for(const key of keys){if(typeof key!=='string'||allowed&&!allowed.has(key))fail('mapping-format');const d=Object.getOwnPropertyDescriptor(value,key);if(!d||!Object.hasOwn(d,'value'))fail('mapping-format');copy[key]=d.value;}return copy;}
function dense(value){if(!Array.isArray(value)||![Array.prototype,null].includes(Object.getPrototypeOf(value)))fail('boundary-limit');const length=Object.getOwnPropertyDescriptor(value,'length')?.value;if(!Number.isInteger(length)||length<1||length>LIMITS.boundaries)fail('boundary-limit');if(Reflect.ownKeys(value).length!==length+1)fail('mapping-format');const copy=[];for(let i=0;i<length;i++){const item=Object.getOwnPropertyDescriptor(value,String(i));if(!item||!Object.hasOwn(item,'value'))fail('mapping-format');copy.push(item.value);}return copy;}
function idValue(s){if(typeof s!=='string'||!s||s.length>LIMITS.idChars||/[\s\x00-\x1f\x7f]/.test(s))fail('identity');return s;}
function tokens(n,key){return words(n.attrs[key]);}
export function resolvePath(from,href){if(typeof href!=='string'||!href||href.length>LIMITS.pathChars*3||href.startsWith('/')||/[\\?#\x00-\x20\x7f]/.test(href)||/^[a-z][a-z0-9+.-]*:/i.test(href)||/%2f|%5c/i.test(href))fail('resource-path');let decoded;try{decoded=decodeURIComponent(href);}catch{fail('resource-path');}const parts=from?from.split('/').slice(0,-1):[];for(const segment of decoded.split('/')){if(segment==='.')continue;if(segment==='..'){if(!parts.length)fail('resource-path');parts.pop();}else if(segment)parts.push(segment);else fail('resource-path');}const path=parts.join('/');if(!safePath(path)||path.endsWith('/'))fail('resource-path');return path;}
function relativeHref(from,to){const a=from.split('/').slice(0,-1),b=to.split('/');while(a.length&&b.length&&a[0]===b[0]){a.shift();b.shift();}return [...a.map(()=>'..'),...b.map(encodeURIComponent)].join('/');}
function parseEntry(entry,budget){if(!entry)fail('missing-resource');if(entry.bytes.length>LIMITS.xmlBytes||budget.bytes+entry.bytes.length>LIMITS.xmlBytesTotal)fail('xml-total-limit');const source=decode(entry.bytes),root=xml(source),nodes=walk(root);budget.bytes+=entry.bytes.length;budget.nodes+=nodes.length;budget.namespace+=root.namespaceWorkUnits;if(budget.nodes>LIMITS.xmlNodesTotal||budget.namespace>LIMITS.namespaceWorkUnitsTotal)fail('xml-total-limit');const ids=new Set();for(const n of nodes){for(const val of [n.attrs.id,attr(n,NS.xml,'id')].filter(x=>x!==undefined&&x!==null)){idValue(val);if(ids.has(val))fail('duplicate-id');ids.add(val);}}return {source,root,nodes,ids,entry};}
function hidden(n){return Object.hasOwn(n.attrs,'hidden')||Object.hasOwn(n.attrs,'inert')||String(n.attrs['aria-hidden']).toLowerCase()==='true';}
function blockReason(node,body){for(let ancestor=body;ancestor;ancestor=ancestor.parent)if(hidden(ancestor))return 'hidden';for(let n=node;n&&n!==body;n=n.parent){if(hidden(n))return 'hidden';if(n!==node&&(n.ns!==NS.xhtml||!containers.has(n.local)))return 'unsupported-ancestor';}if(hidden(body))return 'hidden';for(const n of walk(node)){if(n.ns!==NS.xhtml||n!==node&&!inline.has(n.local))return 'unsupported-structure';if(hidden(n))return 'hidden';if(n.textSegments.some(s=>s.cdata))return 'cdata';}return null;}
function blockSegments(node){return walk(node).flatMap(n=>n.textSegments).sort((a,b)=>a.start-b.start);}
function normalizedBlock(segments,at=null){let normalized='',pending=null;for(const segment of segments){let offset=0;for(const c of segment.text){const location={segment,offset};if(/[ \t\r\n]/.test(c)){if(normalized&&!pending)pending=location;}else{if(pending){if(at===normalized.length)return pending;normalized+=' ';pending=null;}if(at===normalized.length)return location;normalized+=c;}offset++;}}return at===null?normalized:null;}
function rawPosition(segment,offset,source){let raw=segment.start,cp=0;while(raw<segment.end){if(cp===offset)return raw;const c=source[raw];if(c==='&'){const end=source.indexOf(';',raw);if(end<0||end>=segment.end)fail('text-position');raw=end+1;}else if(c==='\r'&&source[raw+1]==='\n')raw+=2;else raw+=source.codePointAt(raw)>0xffff?2:1;cp++;}if(cp===offset)return raw;fail('text-position');}
function inspectXhtml(doc){if(!is(doc.root,NS.xhtml,'html'))fail('xhtml-root');const body=one(direct(doc.root,NS.xhtml,'body'),'xhtml-body');for(const n of doc.nodes){if(n!==doc.root&&attr(n,NS.epub,'prefix')!==null)fail('property-prefix-location');n.semanticPrefixes=prefixState(attr(n,NS.epub,'prefix'),n.parent?.semanticPrefixes,'structure');const semanticTypes=words(attr(n,NS.epub,'type')).map(t=>propertyIRI(t,n.semanticPrefixes,VOCAB.structure));if(n.local==='script'||n.local==='foreignObject'||n.ns===NS.xhtml&&forbidden.has(n.local))fail('scripted-content');if(attr(n,NS.xml,'base')!==null||n.ns===NS.xhtml&&n.local==='base')fail('base-uri');if(tokens(n,'role').includes('doc-pagebreak')||semanticTypes.includes(VOCAB.structure+'pagebreak')||semanticTypes.includes(VOCAB.structure+'page-list'))fail('existing-pagination');for(const [key,value]of Object.entries(n.attrs)){if(/^on[a-z]+$/i.test(key.split(':').at(-1))||/^(?:href|src|action)$/i.test(key.split(':').at(-1))&&/^javascript:/i.test(value.replace(/[\x00-\x20]/g,'')))fail('scripted-content');}}return body;}
export async function inspectBook(input,name='book.epub'){
 const zip=await openZip(input),mime=zip.entries.get('mimetype');if(!mime||mime.offset!==0||mime.method!==0||new DataView(mime.local.buffer,mime.local.byteOffset,mime.local.byteLength).getUint16(28,true)!==0||decode(mime.bytes)!=='application/epub+zip')fail('epub-mimetype');for(const path of zip.entries.keys())if(/^META-INF\/(?:encryption|signatures)\.xml$/i.test(path))fail('protected-package');
 const budget={bytes:0,nodes:0,namespace:0},container=parseEntry(zip.entries.get('META-INF/container.xml'),budget);if(!is(container.root,NS.ocf,'container'))fail('container');const roots=one(direct(container.root,NS.ocf,'rootfiles'),'container'),rootfile=one(direct(roots,NS.ocf,'rootfile'),'multiple-packages');if(rootfile.attrs['media-type']!=='application/oebps-package+xml'||!safePath(rootfile.attrs['full-path']))fail('package-root');const packagePart=rootfile.attrs['full-path'],packageDoc=parseEntry(zip.entries.get(packagePart),budget),pkg=packageDoc.root;if(!is(pkg,NS.opf,'package')||pkg.attrs.version!=='3.0')fail('package-version');if(attr(pkg,NS.xml,'base')!==null)fail('base-uri');const propertyPrefixes=prefixState(pkg.attrs.prefix);
 const metadata=one(direct(pkg,NS.opf,'metadata'),'metadata'),manifestNode=one(direct(pkg,NS.opf,'manifest'),'manifest'),spineNode=one(direct(pkg,NS.opf,'spine'),'spine');const modified=one(direct(metadata,NS.opf,'meta').filter(n=>propertyIRI(n.attrs.property,propertyPrefixes,VOCAB.meta)===VOCAB.dcterms+'modified'&&!n.attrs.refines),'modified-metadata');if(modified.children.length||modified.textSegments.length!==1||modified.textSegments[0].cdata||modified.textSegments[0].start!==modified.openEnd||modified.textSegments[0].end!==modified.closeStart||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$/.test(modified.text))fail('modified-metadata');timestamp(modified.text);
 for(const n of packageDoc.nodes){if(n!==pkg&&Object.hasOwn(n.attrs,'prefix'))fail('property-prefix-location');if(attr(n,NS.xml,'base')!==null)fail('base-uri');if(is(n,NS.opf,'meta')){const property=propertyIRI(n.attrs.property,propertyPrefixes,VOCAB.meta),value=normalizeQuote(n.text);if(property===VOCAB.rendition+'layout'&&value!=='reflowable')fail('fixed-layout');if(property===VOCAB.meta+'pageBreakSource'||property===VOCAB.meta+'source-of'&&value==='pagination'||property===VOCAB.schema+'accessibilityFeature'&&['pageBreakMarkers','pageNavigation','printPageNumbers'].includes(value))fail('existing-pagination');}if(tokens(n,'properties').map(t=>propertyIRI(t,propertyPrefixes,is(n,NS.opf,'itemref')?VOCAB.itemref:VOCAB.item)).some(p=>p===VOCAB.item+'scripted'||p===VOCAB.item+'remote-resources'||p.startsWith(VOCAB.rendition+'layout-')&&p!==VOCAB.rendition+'layout-reflowable'))fail('unsupported-profile');}
 const manifest=new Map(),manifestParts=new Set(),navs=[];for(const n of manifestNode.children){if(!is(n,NS.opf,'item'))fail('manifest');const id=idValue(n.attrs.id),part=resolvePath(packagePart,n.attrs.href),type=n.attrs['media-type'];if(manifest.has(id)||manifestParts.has(part)||!zip.entries.has(part))fail('manifest-identity');if(n.attrs['media-overlay']||/javascript|ecmascript|smil/i.test(type??''))fail('unsupported-profile');const item={id,part,type,properties:tokens(n,'properties').map(t=>propertyIRI(t,propertyPrefixes,VOCAB.item))};manifest.set(id,item);manifestParts.add(part);if(item.properties.includes(VOCAB.item+'nav'))navs.push(item);}
 const navItem=one(navs,'navigation');if(navItem.type!=='application/xhtml+xml')fail('navigation');const docs=new Map();for(const item of manifest.values())if(item.type==='application/xhtml+xml'){const doc=parseEntry(zip.entries.get(item.part),budget);doc.body=inspectXhtml(doc);doc.part=item.part;doc.hash=await sha256(doc.entry.bytes);docs.set(item.part,doc);}
 for(const item of manifest.values())if(item.type==='image/svg+xml'){const svg=parseEntry(zip.entries.get(item.part),budget);for(const n of svg.nodes){if(n.local==='script'||n.local==='foreignObject')fail('scripted-content');for(const [key,value]of Object.entries(n.attrs))if(/^on[a-z]+$/i.test(key.split(':').at(-1))||/^(?:href|src)$/i.test(key.split(':').at(-1))&&/^javascript:/i.test(value.replace(/[\x00-\x20]/g,'')))fail('scripted-content');}}
 const nav=docs.get(navItem.part);if(!nav)fail('navigation');const toc=nav.nodes.filter(n=>is(n,NS.xhtml,'nav')&&words(attr(n,NS.epub,'type')).some(t=>propertyIRI(t,n.semanticPrefixes,VOCAB.structure)===VOCAB.structure+'toc'));if(toc.length!==1||nav.body.closeStart<nav.body.openEnd)fail('navigation');let tocInBody=false;for(let parent=toc[0].parent;parent;parent=parent.parent)if(parent===nav.body)tocInBody=true;if(!tocInBody)fail('navigation');if(nav.ids.has('pt-page-list'))fail('marker-id-collision');
 const spine=[],usedSpine=new Set();let totalText=0,totalBlocks=0;for(const [i,n]of spineNode.children.entries()){if(!is(n,NS.opf,'itemref'))fail('spine');const item=manifest.get(n.attrs.idref);if(!item||item.type!=='application/xhtml+xml'||usedSpine.has(item.part))fail('spine-identity');usedSpine.add(item.part);if(i>=LIMITS.spine)fail('spine-limit');const doc=docs.get(item.part),titleNode=doc.nodes.find(n=>is(n,NS.xhtml,'title')),title=titleNode?normalizeQuote(titleNode.text).slice(0,200):item.id;const chapter={idref:item.id,part:item.part,order:i+1,title,linear:n.attrs.linear!=='no',doc,blocks:[],unsupportedBlocks:0,unsupportedReasons:{}};
  for(const n of walk(doc.body)){if(n.ns!==NS.xhtml||!blocks.has(n.local))continue;if(++totalBlocks>LIMITS.blocks)fail('text-limit');const reason=item.part===navItem.part?'navigation-document':!chapter.linear?'nonlinear-document':blockReason(n,doc.body);if(reason){chapter.unsupportedBlocks++;chapter.unsupportedReasons[reason]=(chapter.unsupportedReasons[reason]??0)+1;continue;}const segments=blockSegments(n),text=normalizedBlock(segments);totalText+=text.length;if(totalText>LIMITS.textChars)fail('text-limit');if(text)chapter.blocks.push({node:n,segments,text,ordinal:chapter.blocks.length+1});}
  spine.push(chapter);
 }if(!spine.length)fail('spine-limit');const inputHash=await sha256(zip.bytes),title=direct(metadata,NS.dc,'title')[0]?.text??'Untitled';const model={schema:'page-thread-inspection-v1',engineVersion:VERSION,input:{name:textValue(name,512,'input-name'),bytes:zip.bytes.length,sha256:inputHash},title:title.slice(0,200),spine:spine.map(({doc,blocks,...s})=>({...s,eligibleBlocks:blocks.length})),stats:{spineDocuments:spine.length,eligibleBlocks:spine.reduce((n,c)=>n+c.blocks.length,0),unsupportedBlocks:spine.reduce((n,c)=>n+c.unsupportedBlocks,0),normalizedTextCharacters:totalText,entries:zip.entries.size},limits:LIMITS,profile:PROFILE};return {zip,packagePart,packageDoc,metadata,modified,manifest,navPart:navItem.part,nav,docs,spine,model};
}
function checkedRecords(records){const values=dense(records),ids=new Set();return values.map(value=>{const record=plain(value,RECORD_KEYS),decisionId=idValue(record.decisionId);if(ids.has(decisionId))fail('duplicate-decision');ids.add(decisionId);const result={decisionId,label:textValue(record.label,LIMITS.labelChars,'label'),phrase:textValue(record.phrase,LIMITS.phraseChars,'phrase')};if(Object.hasOwn(record,'candidateId'))result.candidateId=record.candidateId;return result;});}
export function findCandidates(ctx,records){const checked=checkedRecords(records),results=[];let work=0,total=0;for(const record of checked){const phrase=normalizeQuote(record.phrase),candidates=[];for(const chapter of ctx.spine)for(const block of chapter.blocks){work+=block.text.length;if(work>LIMITS.searchWork)fail('search-work-limit');for(let index=block.text.indexOf(phrase);index!==-1;index=block.text.indexOf(phrase,index+1)){if(candidates.length>=LIMITS.candidatesPerBoundary||++total>LIMITS.candidatesTotal)fail('candidate-limit');work+=block.text.length;if(work>LIMITS.searchWork)fail('search-work-limit');const {segment,offset}=normalizedBlock(block.segments,index),sourcePath=segment.parent.path,rawOffset=rawPosition(segment,offset,chapter.doc.source);const id=`${chapter.part}#${sourcePath.join('.')}/${segment.textNodeIndex}:${offset}`;candidates.push({id,sourcePart:chapter.part,sourcePartSha256:chapter.doc.hash,spineIdref:chapter.idref,spineOrder:chapter.order,chapterTitle:chapter.title,sourcePath,textNodeIndex:segment.textNodeIndex,offset,rawOffset,blockOrdinal:block.ordinal,contextBefore:block.text.slice(Math.max(0,index-70),index),matchText:block.text.slice(index,index+phrase.length),contextAfter:block.text.slice(index+phrase.length,index+phrase.length+100)});}}
 results.push({...record,normalizedPhrase:phrase,candidateCount:candidates.length,candidates,status:candidates.length===0?'missing':candidates.length===1?'one':'multiple'});}return results;}
function timestamp(value){if(typeof value!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().replace('.000Z','Z')!==value)fail('modified-date');return value;}
export function previewMapping(ctx,draft){draft=plain(draft,MAPPING_KEYS);if(draft.schema!=='page-thread-mapping-v1'||draft.inputSha256!==ctx.model.input.sha256)fail('stale-mapping');if(draft.whitespace!==WHITESPACE)fail('whitespace-profile');const paginationSource=textValue(draft.paginationSource,LIMITS.sourceChars,'pagination-source'),modifiedAfter=timestamp(draft.modifiedAfter),records=checkedRecords(draft.boundaries);if(modifiedAfter<ctx.modified.text)fail('modified-date');const found=findCandidates(ctx,records),rows=[];let previous=[0,-1];for(const [i,result]of found.entries()){const choice=records[i].candidateId;if(typeof choice!=='string')fail('unresolved-boundary');const selectedIndex=result.candidates.findIndex(c=>c.id===choice);if(selectedIndex<0)fail('stale-location');const candidate=result.candidates[selectedIndex],position=[candidate.spineOrder,candidate.rawOffset];if(position[0]<previous[0]||position[0]===previous[0]&&position[1]<=previous[1])fail('boundary-order');previous=position;const markerId=`pt-page-${String(i+1).padStart(4,'0')}`;if(ctx.docs.get(candidate.sourcePart).ids.has(markerId))fail('marker-id-collision');rows.push({...candidate,...records[i],candidateCount:result.candidateCount,selectedOccurrence:selectedIndex+1,markerId,href:relativeHref(ctx.navPart,candidate.sourcePart)+'#'+markerId});}
 const mapping={schema:'page-thread-mapping-v1',inputSha256:ctx.model.input.sha256,paginationSource,modifiedAfter,whitespace:WHITESPACE,boundaries:rows.map(r=>({decisionId:r.decisionId,label:r.label,phrase:r.phrase,candidateId:r.id}))};if(encode(mappingText(mapping)).length>LIMITS.mappingBytes)fail('mapping-size');return {mapping,rows};}
export function mappingText(value){const mapping=plain(value,MAPPING_KEYS);for(const key of ['schema','inputSha256','paginationSource','modifiedAfter','whitespace'])if(typeof mapping[key]!=='string')fail('mapping-format');const boundaries=dense(mapping.boundaries).map(value=>{const row=plain(value,RECORD_KEYS);for(const key of RECORD_KEYS)if(typeof row[key]!=='string')fail('mapping-format');return row;});Object.setPrototypeOf(boundaries,null);mapping.boundaries=boundaries;return JSON.stringify(mapping,null,2)+'\n';}
function patch(source,edits){for(const edit of edits.sort((a,b)=>b.start-a.start)){source=source.slice(0,edit.start)+edit.text+source.slice(edit.end);}return source;}
export async function applyMapping(ctx,draft){const {mapping,rows}=previewMapping(ctx,draft),edits=new Map(),add=(part,edit)=>{if(!edits.has(part))edits.set(part,[]);edits.get(part).push(edit);};for(const row of rows)add(row.sourcePart,{start:row.rawOffset,end:row.rawOffset,text:`<span xmlns="${NS.xhtml}" xmlns:epub="${NS.epub}" id="${row.markerId}" epub:type="pagebreak" role="doc-pagebreak" aria-label="${escapeXML(row.label)}"/>`});
 const additions={pageListId:'pt-page-list',pageListLabel:'Pages / ページ',metadata:[{property:'pageBreakSource',value:mapping.paginationSource},{property:'schema:accessibilityFeature',value:'pageBreakMarkers'},{property:'schema:accessibilityFeature',value:'pageNavigation'}]};
 const navText=`<nav xmlns="${NS.xhtml}" xmlns:epub="${NS.epub}" id="${additions.pageListId}" epub:type="page-list" hidden="hidden"><h2>${additions.pageListLabel}</h2><ol>${rows.map(r=>`<li><a href="${escapeXML(r.href)}">${escapeXML(r.label)}</a></li>`).join('')}</ol></nav>`;
 add(ctx.navPart,{start:ctx.nav.body.closeStart,end:ctx.nav.body.closeStart,text:navText});
 add(ctx.packagePart,{start:ctx.metadata.closeStart,end:ctx.metadata.closeStart,text:additions.metadata.map(m=>`<meta xmlns="${NS.opf}" property="${m.property}">${escapeXML(m.value)}</meta>`).join('')});
 add(ctx.packagePart,{start:ctx.modified.openEnd,end:ctx.modified.closeStart,text:mapping.modifiedAfter});
 const changes=new Map();for(const [part,partEdits]of edits)changes.set(part,encode(patch(decode(ctx.zip.entries.get(part).bytes),partEdits)));const output=writeZip(ctx.zip,changes),outZip=await openZip(output),changedParts=[],unchangedParts=[];if(outZip.entries.get('mimetype')?.offset!==0)fail('verify-mimetype');
 for(const [part,entry]of ctx.zip.entries){const after=outZip.entries.get(part);if(!after)fail('verify-parts');const beforeSha256=await sha256(entry.bytes),afterSha256=await sha256(after.bytes);if(changes.has(part))changedParts.push({part,beforeSha256,afterSha256});else{if(beforeSha256!==afterSha256)fail('verify-unchanged');unchangedParts.push({part,sha256:beforeSha256});}}
 const verifiedDocuments=new Map();for(const part of changes.keys()){const doc=xml(decode(outZip.entries.get(part).bytes)),ids=new Map();for(const n of walk(doc))if(n.attrs.id){if(ids.has(n.attrs.id))fail('verify-identity');ids.set(n.attrs.id,n);}verifiedDocuments.set(part,{doc,ids});}
 for(const row of rows){const marker=verifiedDocuments.get(row.sourcePart).ids.get(row.markerId);if(!is(marker,NS.xhtml,'span')||marker.attrs['aria-label']!==row.label||marker.attrs.role!=='doc-pagebreak'||attr(marker,NS.epub,'type')!=='pagebreak')fail('verify-marker');}
 const receipt={schema:'page-thread-receipt-v1',engineVersion:VERSION,profile:PROFILE,inputSha256:ctx.model.input.sha256,outputSha256:await sha256(output),mappingSha256:await sha256(encode(mappingText(mapping))),packagePart:ctx.packagePart,navPart:ctx.navPart,paginationSource:mapping.paginationSource,modified:{sourcePath:ctx.modified.path,before:ctx.modified.text,after:mapping.modifiedAfter},boundaries:rows.map(r=>({decisionId:r.decisionId,label:r.label,phrase:r.phrase,sourcePart:r.sourcePart,sourcePartSha256:r.sourcePartSha256,spineIdref:r.spineIdref,sourcePath:r.sourcePath,textNodeIndex:r.textNodeIndex,offset:r.offset,markerId:r.markerId,candidateCount:r.candidateCount,selectedOccurrence:r.selectedOccurrence})),additions,changedParts,unchangedParts,limits:LIMITS,verification:{reopened:true,unaffectedEntriesByteIdentical:true,editorialBoundaryCorrectness:false,universalReaderCompatibility:false,overallAccessibilityConformance:false}};return {output,receipt,mapping};}
