import {LIMITS,fail} from './limits.mjs';
const UTF8=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true});export const encode=s=>new TextEncoder().encode(s);export const decode=b=>{try{return UTF8.decode(b);}catch{fail('encoding');}};
export function safePath(name){return typeof name==='string'&&!!name&&name.length<=LIMITS.pathChars&&!/[\\\x00-\x1f\x7f:%?#]/.test(name)&&!name.startsWith('/')&&name===name.normalize('NFC')&&name.split('/').every((p,i,a)=>p!=='.'&&p!=='..'&&(p!==''||i===a.length-1));}
export function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
export async function sha256(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function checkExtra(v,start,length){let p=start;while(p<start+length){if(p+4>start+length)fail('zip-extra');const id=v.getUint16(p,true),n=v.getUint16(p+2,true);if(p+4+n>start+length||[1,0x9901,0x7075,0x6375].includes(id))fail('zip-extra');p+=4+n;}}
export function directory(input){
 // Own one ordinary Uint8Array before slicing headers or awaiting inflation.
 // Buffer.slice aliases storage; ArrayBuffer construction alone is also a view.
 if(!(input instanceof Uint8Array)&&!(input instanceof ArrayBuffer))fail('input-type');if(input.byteLength>LIMITS.inputBytes||input.byteLength<22)fail('input-size');const bytes=new Uint8Array(input instanceof Uint8Array?input:new Uint8Array(input));
 if(bytes.length>LIMITS.inputBytes||bytes.length<22)fail('input-size');if(bytes[0]===0xd0&&bytes[1]===0xcf)fail('encrypted-format');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.length),n=bytes.length;let end=-1;for(let i=n-22;i>=Math.max(0,n-65557);i--)if(v.getUint32(i,true)===0x06054b50&&i+22+v.getUint16(i+20,true)===n){end=i;break;}if(end<0)fail('zip-header');const count=v.getUint16(end+10,true),size=v.getUint32(end+12,true),start=v.getUint32(end+16,true);if(v.getUint16(end+4,true)||v.getUint16(end+6,true)||count!==v.getUint16(end+8,true)||count===65535||size===0xffffffff||start===0xffffffff)fail('zip-format');if(!count||count>LIMITS.entries||start+size!==end)fail('zip-limit');let p=start,total=0;const entries=new Map(),spans=[],folded=new Set();
 for(let i=0;i<count;i++){if(p+46>end||v.getUint32(p,true)!==0x02014b50)fail('zip-central');const flags=v.getUint16(p+8,true),method=v.getUint16(p+10,true),crc=v.getUint32(p+16,true),compressed=v.getUint32(p+20,true),size=v.getUint32(p+24,true),nl=v.getUint16(p+28,true),xl=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),offset=v.getUint32(p+42,true);if(p+46+nl+xl+cl>end)fail('zip-central');checkExtra(v,p+46+nl,xl);const nameBytes=bytes.subarray(p+46,p+46+nl);if(!(flags&0x800)&&nameBytes.some(b=>b>127))fail('zip-encoding');const name=decode(nameBytes);if(flags&0x800)decode(bytes.subarray(p+46+nl+xl,p+46+nl+xl+cl));if(!safePath(name)||entries.has(name)||folded.has(name.toLowerCase()))fail('zip-path');folded.add(name.toLowerCase());if(flags&~(0x0800|0x0008|0x0006)||![0,8].includes(method)||v.getUint16(p+34,true))fail('zip-format');if((v.getUint32(p+38,true)>>>16&0xf000)===0xa000)fail('zip-link');if(size>LIMITS.entryBytes||total+size>LIMITS.totalBytes||size>Math.max(1024,compressed*LIMITS.ratio))fail('zip-limit');total+=size;
 if(offset+30>start||v.getUint32(offset,true)!==0x04034b50)fail('zip-local');const lf=v.getUint16(offset+6,true),lm=v.getUint16(offset+8,true),ln=v.getUint16(offset+26,true),lx=v.getUint16(offset+28,true),data=offset+30+ln+lx;if(data>start)fail('zip-local');checkExtra(v,offset+30+ln,lx);if(lf!==flags||lm!==method||data+compressed>start||decode(bytes.subarray(offset+30,offset+30+ln))!==name)fail('zip-local');if(!(flags&8)&&(v.getUint32(offset+14,true)!==crc||v.getUint32(offset+18,true)!==compressed||v.getUint32(offset+22,true)!==size))fail('zip-local');let spanEnd=data+compressed;if(flags&8){let d=spanEnd;if(d+4<=start&&v.getUint32(d,true)===0x08074b50)d+=4;if(d+12>start||v.getUint32(d,true)!==crc||v.getUint32(d+4,true)!==compressed||v.getUint32(d+8,true)!==size)fail('zip-descriptor');spanEnd=d+12;}
 spans.push([offset,spanEnd]);entries.set(name,{name,flags,method,crc,compressed,size,data,offset,spanEnd,central:bytes.slice(p,p+46+nl+xl+cl),local:bytes.slice(offset,spanEnd)});p+=46+nl+xl+cl;
 }if(p!==end)fail('zip-central');spans.sort((a,b)=>a[0]-b[0]);if(spans[0][0]!==0)fail('zip-preamble');for(let i=1;i<spans.length;i++)if(spans[i][0]!==spans[i-1][1])fail('zip-overlap');if(spans.at(-1)[1]!==start)fail('zip-gap');return {entries,endRecord:bytes.slice(end),total,bytes};
}
async function inflate(bytes,e){let result;if(e.method===0)result=bytes.slice(e.data,e.data+e.compressed);else{if(typeof DecompressionStream==='undefined')fail('zip-unavailable');let stream;try{stream=new Blob([bytes.subarray(e.data,e.data+e.compressed)]).stream().pipeThrough(new DecompressionStream('deflate-raw'));}catch{fail('zip-unavailable');}const reader=stream.getReader(),chunks=[];let length=0;try{while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>e.size||length>LIMITS.entryBytes){await reader.cancel();fail('zip-inflation');}chunks.push(value);}}catch(error){if(error.code)throw error;fail('zip-inflation');}result=new Uint8Array(length);let p=0;for(const c of chunks){result.set(c,p);p+=c.length;}}if(result.length!==e.size||crc32(result)!==e.crc)fail('zip-integrity');return result;}
export async function openZip(input){const d=directory(input),bytes=d.bytes;for(const e of d.entries.values())e.bytes=await inflate(bytes,e);return {...d,bytes};}
export function writeZip(zip,changes){if(!changes.size)return zip.bytes.slice();const locals=[],centralByName=new Map();let offset=0;for(const e of [...zip.entries.values()].sort((a,b)=>a.offset-b.offset)){let local=e.local,central=e.central.slice(),cv=new DataView(central.buffer);if(changes.has(e.name)){const bytes=changes.get(e.name);if(bytes.length>LIMITS.entryBytes)fail('output-size');const name=encode(e.name),header=new Uint8Array(30),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,e.flags&0x800,true);v.setUint16(10,new DataView(e.local.buffer,e.local.byteOffset).getUint16(10,true),true);v.setUint16(12,new DataView(e.local.buffer,e.local.byteOffset).getUint16(12,true),true);v.setUint32(14,crc32(bytes),true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);local=concat([header,name,bytes]);cv.setUint16(6,20,true);cv.setUint16(8,e.flags&0x800,true);cv.setUint16(10,0,true);cv.setUint32(16,crc32(bytes),true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);}cv.setUint32(42,offset,true);locals.push(local);centralByName.set(e.name,central);offset+=local.length;}const central=concat([...zip.entries.keys()].map(name=>centralByName.get(name))),end=zip.endRecord.slice(),ev=new DataView(end.buffer);ev.setUint32(12,central.length,true);ev.setUint32(16,offset,true);const output=concat([...locals,central,end]);if(output.length>LIMITS.outputBytes)fail('output-size');return output;}
export function concat(chunks){const n=chunks.reduce((s,c)=>s+c.length,0);if(n>LIMITS.outputBytes)fail('output-size');const out=new Uint8Array(n);let p=0;for(const c of chunks){out.set(c,p);p+=c.length;}return out;}
